### ISSUE TITLE
Selecting Similar Number Machines

### ISSUE THREAD

**Issue by micahmones** [mattnazari/WaShare#12]
Selecting Washer 1 + Dryer 1 results in nothing being booked
Washer 1 + Dryer 2 = Both booked
Washer 1 + Washer 2 = Both Booked
Washer 1 + Dryer 1 = None Booked

**Comment by mattnazari** [comment]
mmm so just to be clear when you book:
Washer 2 + Dryer 2 = None booked
because you selected the machines with the same number ?

**Comment by micahmones** [comment]
Yes cuz currently it does a check if the number is in an array

**Comment by micahmones** [comment]
Fixed with https://github.com/mattnazari/WaShare/pull/49
