### ISSUE TITLE
Backend Database

### ISSUE THREAD

**Issue by micahmones** [mattnazari/WaShare#38]
Need to implement a database to store:
- User logins
- Payment info
- Payment history

**Comment by mattnazari** [comment]
lets wait until ramin goes into more detail about the backend part.
i recall him saying that there was gonna be an easier way of tackling the back end
this year.

**Comment by mattnazari** [comment]
talked to Ramin he said, most of the work will be done
on the server side, and that henry will elaborate

**Comment by micahmones** [comment]
still need to track user information
